# Blog settings
permalink: /blog/:title
disqus: jidon333

# My variables
name: jidon333
description: jidon333's blog
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
url: https://jidon333.github.io

# Google
google-analytics:
  id: "UA-89712100-1"